resource_types:
  - name: bitbucket-pr
    type: registry-image
    source:
      repository: n7docker/concourse-bitbucket-pr

resources:
  - name: pull-request
    type: bitbucket-pr
    check_every: 1m
    source:
      workspace: example_company
      slug: repository_name
      username: ((ci_user))
      password: ((ci_pass))
      debug: true

jobs:
  - name: foo
    plan:
      - get: pull-request
        trigger: true
        version: every
      - task: do-it
        config:
          inputs:
            - name: pull-request
          outputs:
            - name: pull-request
          platform: linux
          image_resource:
            source:
              repository: alpine
            type: docker-image
          run:
            path: echo
            args:
              - "I'm really doing it!"
  - name: bar
    plan:
      - get: pull-request
        trigger: true
        passed:
          - foo
      - put: pull-request
        params:
          repo_path: pull-request
          action: set:commit.build.status
          status: INPROGRESS
          url: example.com
          name: PR resource test
          description: Some userful description
      - task: and-it
        config:
          inputs:
            - name: pull-request
          outputs:
            - name: pull-request
          platform: linux
          image_resource:
            source:
              repository: alpine
            type: docker-image
          run:
            path: sh
            args:
              - -exc
              - |
                  find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
        on_failure:
          do:
          - put: pull-request
            params:
              repo_path: pull-request
              action: set:commit.build.status
              status: FAILED
              url: https://ci.example.com/builds/$BUILD_ID
              name: "Concourse CI Assemble / Test"
              description: "Buil failed https://ci.example.com/builds/$BUILD_ID"
        on_success:
          do:
          - put: pull-request
            params:
              repo_path: pull-request
              action: set:commit.build.status
              status: SUCCESSFUL
              url: https://ci.example.com/builds/$BUILD_ID
              name: "Concourse CI Assemble / Test"
              description: "Buil passed https://ci.example.com/builds/$BUILD_ID"


